# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'badge.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(790, 588)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(699, 553))
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 771, 511))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_Uart = QtGui.QWidget()
        self.tab_Uart.setObjectName(_fromUtf8("tab_Uart"))
        self.comboBox_UartPort = QtGui.QComboBox(self.tab_Uart)
        self.comboBox_UartPort.setGeometry(QtCore.QRect(10, 10, 171, 27))
        self.comboBox_UartPort.setObjectName(_fromUtf8("comboBox_UartPort"))
        self.comboBox_UartBaud = QtGui.QComboBox(self.tab_Uart)
        self.comboBox_UartBaud.setGeometry(QtCore.QRect(190, 10, 161, 27))
        self.comboBox_UartBaud.setObjectName(_fromUtf8("comboBox_UartBaud"))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.comboBox_UartBaud.addItem(_fromUtf8(""))
        self.pushButton_UartConnect = QtGui.QPushButton(self.tab_Uart)
        self.pushButton_UartConnect.setGeometry(QtCore.QRect(640, 10, 111, 27))
        self.pushButton_UartConnect.setCheckable(True)
        self.pushButton_UartConnect.setObjectName(_fromUtf8("pushButton_UartConnect"))
        self.textEdit_UartConsole = QtGui.QTextEdit(self.tab_Uart)
        self.textEdit_UartConsole.setGeometry(QtCore.QRect(10, 50, 741, 381))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.textEdit_UartConsole.setPalette(palette)
        self.textEdit_UartConsole.setReadOnly(True)
        self.textEdit_UartConsole.setObjectName(_fromUtf8("textEdit_UartConsole"))
        self.lineEdit_UartInput = QtGui.QLineEdit(self.tab_Uart)
        self.lineEdit_UartInput.setGeometry(QtCore.QRect(10, 440, 611, 27))
        self.lineEdit_UartInput.setObjectName(_fromUtf8("lineEdit_UartInput"))
        self.comboBox_UartTerminator = QtGui.QComboBox(self.tab_Uart)
        self.comboBox_UartTerminator.setGeometry(QtCore.QRect(630, 440, 121, 27))
        self.comboBox_UartTerminator.setObjectName(_fromUtf8("comboBox_UartTerminator"))
        self.comboBox_UartTerminator.addItem(_fromUtf8(""))
        self.comboBox_UartTerminator.addItem(_fromUtf8(""))
        self.comboBox_UartTerminator.addItem(_fromUtf8(""))
        self.comboBox_UartTerminator.addItem(_fromUtf8(""))
        self.pushButton_UartRefresh = QtGui.QPushButton(self.tab_Uart)
        self.pushButton_UartRefresh.setGeometry(QtCore.QRect(360, 10, 61, 27))
        self.pushButton_UartRefresh.setObjectName(_fromUtf8("pushButton_UartRefresh"))
        self.tabWidget.addTab(self.tab_Uart, _fromUtf8(""))
        self.tab_Spi = QtGui.QWidget()
        self.tab_Spi.setObjectName(_fromUtf8("tab_Spi"))
        self.textEdit_SpiConsole = QtGui.QTextEdit(self.tab_Spi)
        self.textEdit_SpiConsole.setGeometry(QtCore.QRect(10, 90, 741, 381))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.textEdit_SpiConsole.setPalette(palette)
        self.textEdit_SpiConsole.setReadOnly(True)
        self.textEdit_SpiConsole.setObjectName(_fromUtf8("textEdit_SpiConsole"))
        self.lineEdit_SpiFilePath = QtGui.QLineEdit(self.tab_Spi)
        self.lineEdit_SpiFilePath.setGeometry(QtCore.QRect(10, 20, 461, 27))
        self.lineEdit_SpiFilePath.setObjectName(_fromUtf8("lineEdit_SpiFilePath"))
        self.comboBox_SpiOperation = QtGui.QComboBox(self.tab_Spi)
        self.comboBox_SpiOperation.setGeometry(QtCore.QRect(480, 20, 161, 27))
        self.comboBox_SpiOperation.setObjectName(_fromUtf8("comboBox_SpiOperation"))
        self.comboBox_SpiOperation.addItem(_fromUtf8(""))
        self.comboBox_SpiOperation.addItem(_fromUtf8(""))
        self.comboBox_SpiOperation.addItem(_fromUtf8(""))
        self.comboBox_SpiOperation.addItem(_fromUtf8(""))
        self.pushButton_SpiRun = QtGui.QPushButton(self.tab_Spi)
        self.pushButton_SpiRun.setGeometry(QtCore.QRect(650, 20, 99, 27))
        self.pushButton_SpiRun.setCheckable(False)
        self.pushButton_SpiRun.setObjectName(_fromUtf8("pushButton_SpiRun"))
        self.line = QtGui.QFrame(self.tab_Spi)
        self.line.setGeometry(QtCore.QRect(10, 55, 741, 21))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.tabWidget.addTab(self.tab_Spi, _fromUtf8(""))
        self.tab_Jtag = QtGui.QWidget()
        self.tab_Jtag.setObjectName(_fromUtf8("tab_Jtag"))
        self.textEdit_JtagConsole = QtGui.QTextEdit(self.tab_Jtag)
        self.textEdit_JtagConsole.setGeometry(QtCore.QRect(10, 90, 741, 381))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.textEdit_JtagConsole.setPalette(palette)
        self.textEdit_JtagConsole.setReadOnly(True)
        self.textEdit_JtagConsole.setObjectName(_fromUtf8("textEdit_JtagConsole"))
        self.comboBox_JtagSelectDevice = QtGui.QComboBox(self.tab_Jtag)
        self.comboBox_JtagSelectDevice.setGeometry(QtCore.QRect(10, 10, 201, 27))
        self.comboBox_JtagSelectDevice.setObjectName(_fromUtf8("comboBox_JtagSelectDevice"))
        self.pushButton_JtagStartServer = QtGui.QPushButton(self.tab_Jtag)
        self.pushButton_JtagStartServer.setGeometry(QtCore.QRect(10, 40, 201, 27))
        self.pushButton_JtagStartServer.setCheckable(True)
        self.pushButton_JtagStartServer.setObjectName(_fromUtf8("pushButton_JtagStartServer"))
        self.pushButton_JtagConnect = QtGui.QPushButton(self.tab_Jtag)
        self.pushButton_JtagConnect.setGeometry(QtCore.QRect(260, 10, 241, 27))
        self.pushButton_JtagConnect.setCheckable(True)
        self.pushButton_JtagConnect.setObjectName(_fromUtf8("pushButton_JtagConnect"))
        self.pushButton_JtagRunGdb = QtGui.QPushButton(self.tab_Jtag)
        self.pushButton_JtagRunGdb.setGeometry(QtCore.QRect(550, 40, 201, 27))
        self.pushButton_JtagRunGdb.setCheckable(True)
        self.pushButton_JtagRunGdb.setObjectName(_fromUtf8("pushButton_JtagRunGdb"))
        self.line_2 = QtGui.QFrame(self.tab_Jtag)
        self.line_2.setGeometry(QtCore.QRect(210, 10, 41, 61))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.tab_Jtag)
        self.line_3.setGeometry(QtCore.QRect(500, 10, 41, 61))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.lineEdit_JtagElfPath = QtGui.QLineEdit(self.tab_Jtag)
        self.lineEdit_JtagElfPath.setGeometry(QtCore.QRect(550, 10, 201, 27))
        self.lineEdit_JtagElfPath.setObjectName(_fromUtf8("lineEdit_JtagElfPath"))
        self.tabWidget.addTab(self.tab_Jtag, _fromUtf8(""))
        self.tab_I2c = QtGui.QWidget()
        self.tab_I2c.setObjectName(_fromUtf8("tab_I2c"))
        self.textEdit_I2cConsole = QtGui.QTextEdit(self.tab_I2c)
        self.textEdit_I2cConsole.setGeometry(QtCore.QRect(10, 90, 741, 381))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.textEdit_I2cConsole.setPalette(palette)
        self.textEdit_I2cConsole.setReadOnly(True)
        self.textEdit_I2cConsole.setObjectName(_fromUtf8("textEdit_I2cConsole"))
        self.line_4 = QtGui.QFrame(self.tab_I2c)
        self.line_4.setGeometry(QtCore.QRect(10, 55, 741, 21))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.lineEdit_I2cFilePath = QtGui.QLineEdit(self.tab_I2c)
        self.lineEdit_I2cFilePath.setGeometry(QtCore.QRect(10, 20, 461, 27))
        self.lineEdit_I2cFilePath.setObjectName(_fromUtf8("lineEdit_I2cFilePath"))
        self.comboBox_I2cOperation = QtGui.QComboBox(self.tab_I2c)
        self.comboBox_I2cOperation.setGeometry(QtCore.QRect(480, 20, 161, 27))
        self.comboBox_I2cOperation.setObjectName(_fromUtf8("comboBox_I2cOperation"))
        self.comboBox_I2cOperation.addItem(_fromUtf8(""))
        self.comboBox_I2cOperation.addItem(_fromUtf8(""))
        self.comboBox_I2cOperation.addItem(_fromUtf8(""))
        self.comboBox_I2cOperation.addItem(_fromUtf8(""))
        self.pushButton_I2cRun = QtGui.QPushButton(self.tab_I2c)
        self.pushButton_I2cRun.setGeometry(QtCore.QRect(650, 20, 99, 27))
        self.pushButton_I2cRun.setCheckable(False)
        self.pushButton_I2cRun.setObjectName(_fromUtf8("pushButton_I2cRun"))
        self.tabWidget.addTab(self.tab_I2c, _fromUtf8(""))
        self.tab_Gpio = QtGui.QWidget()
        self.tab_Gpio.setObjectName(_fromUtf8("tab_Gpio"))
        self.checkBox_d0 = QtGui.QCheckBox(self.tab_Gpio)
        self.checkBox_d0.setGeometry(QtCore.QRect(120, 100, 81, 31))
        self.checkBox_d0.setObjectName(_fromUtf8("checkBox_d0"))
        self.comboBox_d0 = QtGui.QComboBox(self.tab_Gpio)
        self.comboBox_d0.setGeometry(QtCore.QRect(210, 100, 85, 27))
        self.comboBox_d0.setObjectName(_fromUtf8("comboBox_d0"))
        self.comboBox_d0.addItem(_fromUtf8(""))
        self.comboBox_d0.addItem(_fromUtf8(""))
        self.checkBox_d1 = QtGui.QCheckBox(self.tab_Gpio)
        self.checkBox_d1.setGeometry(QtCore.QRect(120, 180, 81, 31))
        self.checkBox_d1.setObjectName(_fromUtf8("checkBox_d1"))
        self.comboBox_d1 = QtGui.QComboBox(self.tab_Gpio)
        self.comboBox_d1.setGeometry(QtCore.QRect(210, 180, 85, 27))
        self.comboBox_d1.setObjectName(_fromUtf8("comboBox_d1"))
        self.comboBox_d1.addItem(_fromUtf8(""))
        self.comboBox_d1.addItem(_fromUtf8(""))
        self.comboBox_d2 = QtGui.QComboBox(self.tab_Gpio)
        self.comboBox_d2.setGeometry(QtCore.QRect(210, 260, 85, 27))
        self.comboBox_d2.setObjectName(_fromUtf8("comboBox_d2"))
        self.comboBox_d2.addItem(_fromUtf8(""))
        self.comboBox_d2.addItem(_fromUtf8(""))
        self.checkBox_d2 = QtGui.QCheckBox(self.tab_Gpio)
        self.checkBox_d2.setGeometry(QtCore.QRect(120, 260, 81, 31))
        self.checkBox_d2.setObjectName(_fromUtf8("checkBox_d2"))
        self.comboBox_d3 = QtGui.QComboBox(self.tab_Gpio)
        self.comboBox_d3.setGeometry(QtCore.QRect(210, 340, 85, 27))
        self.comboBox_d3.setObjectName(_fromUtf8("comboBox_d3"))
        self.comboBox_d3.addItem(_fromUtf8(""))
        self.comboBox_d3.addItem(_fromUtf8(""))
        self.checkBox_d3 = QtGui.QCheckBox(self.tab_Gpio)
        self.checkBox_d3.setGeometry(QtCore.QRect(120, 340, 81, 31))
        self.checkBox_d3.setObjectName(_fromUtf8("checkBox_d3"))
        self.checkBox_d7 = QtGui.QCheckBox(self.tab_Gpio)
        self.checkBox_d7.setGeometry(QtCore.QRect(460, 340, 81, 31))
        self.checkBox_d7.setObjectName(_fromUtf8("checkBox_d7"))
        self.checkBox_d5 = QtGui.QCheckBox(self.tab_Gpio)
        self.checkBox_d5.setGeometry(QtCore.QRect(460, 180, 81, 31))
        self.checkBox_d5.setObjectName(_fromUtf8("checkBox_d5"))
        self.comboBox_d4 = QtGui.QComboBox(self.tab_Gpio)
        self.comboBox_d4.setGeometry(QtCore.QRect(550, 100, 85, 27))
        self.comboBox_d4.setObjectName(_fromUtf8("comboBox_d4"))
        self.comboBox_d4.addItem(_fromUtf8(""))
        self.comboBox_d4.addItem(_fromUtf8(""))
        self.checkBox_d6 = QtGui.QCheckBox(self.tab_Gpio)
        self.checkBox_d6.setGeometry(QtCore.QRect(460, 260, 81, 31))
        self.checkBox_d6.setObjectName(_fromUtf8("checkBox_d6"))
        self.comboBox_d5 = QtGui.QComboBox(self.tab_Gpio)
        self.comboBox_d5.setGeometry(QtCore.QRect(550, 180, 85, 27))
        self.comboBox_d5.setObjectName(_fromUtf8("comboBox_d5"))
        self.comboBox_d5.addItem(_fromUtf8(""))
        self.comboBox_d5.addItem(_fromUtf8(""))
        self.comboBox_d6 = QtGui.QComboBox(self.tab_Gpio)
        self.comboBox_d6.setGeometry(QtCore.QRect(550, 260, 85, 27))
        self.comboBox_d6.setObjectName(_fromUtf8("comboBox_d6"))
        self.comboBox_d6.addItem(_fromUtf8(""))
        self.comboBox_d6.addItem(_fromUtf8(""))
        self.checkBox_d4 = QtGui.QCheckBox(self.tab_Gpio)
        self.checkBox_d4.setGeometry(QtCore.QRect(460, 100, 81, 31))
        self.checkBox_d4.setObjectName(_fromUtf8("checkBox_d4"))
        self.comboBox_d7 = QtGui.QComboBox(self.tab_Gpio)
        self.comboBox_d7.setGeometry(QtCore.QRect(550, 340, 85, 27))
        self.comboBox_d7.setObjectName(_fromUtf8("comboBox_d7"))
        self.comboBox_d7.addItem(_fromUtf8(""))
        self.comboBox_d7.addItem(_fromUtf8(""))
        self.line_5 = QtGui.QFrame(self.tab_Gpio)
        self.line_5.setGeometry(QtCore.QRect(373, 80, 16, 301))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.pushButton_GpioStartInputMonitor = QtGui.QPushButton(self.tab_Gpio)
        self.pushButton_GpioStartInputMonitor.setGeometry(QtCore.QRect(270, 420, 221, 27))
        self.pushButton_GpioStartInputMonitor.setObjectName(_fromUtf8("pushButton_GpioStartInputMonitor"))
        self.tabWidget.addTab(self.tab_Gpio, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Attify Badge Tool", None))
        self.comboBox_UartBaud.setItemText(0, _translate("MainWindow", "110", None))
        self.comboBox_UartBaud.setItemText(1, _translate("MainWindow", "300", None))
        self.comboBox_UartBaud.setItemText(2, _translate("MainWindow", "600", None))
        self.comboBox_UartBaud.setItemText(3, _translate("MainWindow", "1200", None))
        self.comboBox_UartBaud.setItemText(4, _translate("MainWindow", "2400", None))
        self.comboBox_UartBaud.setItemText(5, _translate("MainWindow", "4800", None))
        self.comboBox_UartBaud.setItemText(6, _translate("MainWindow", "9600", None))
        self.comboBox_UartBaud.setItemText(7, _translate("MainWindow", "14400", None))
        self.comboBox_UartBaud.setItemText(8, _translate("MainWindow", "19200", None))
        self.comboBox_UartBaud.setItemText(9, _translate("MainWindow", "38400", None))
        self.comboBox_UartBaud.setItemText(10, _translate("MainWindow", "57600", None))
        self.comboBox_UartBaud.setItemText(11, _translate("MainWindow", "115200", None))
        self.comboBox_UartBaud.setItemText(12, _translate("MainWindow", "128000", None))
        self.comboBox_UartBaud.setItemText(13, _translate("MainWindow", "256000", None))
        self.pushButton_UartConnect.setText(_translate("MainWindow", "Connect", None))
        self.comboBox_UartTerminator.setItemText(0, _translate("MainWindow", "New Line", None))
        self.comboBox_UartTerminator.setItemText(1, _translate("MainWindow", "Carriage Return", None))
        self.comboBox_UartTerminator.setItemText(2, _translate("MainWindow", "CR + LF", None))
        self.comboBox_UartTerminator.setItemText(3, _translate("MainWindow", "No line ending", None))
        self.pushButton_UartRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Uart), _translate("MainWindow", "     UART    ", None))
        self.lineEdit_SpiFilePath.setPlaceholderText(_translate("MainWindow", "Enter File Name and Path", None))
        self.comboBox_SpiOperation.setItemText(0, _translate("MainWindow", "Find Chip", None))
        self.comboBox_SpiOperation.setItemText(1, _translate("MainWindow", "Read", None))
        self.comboBox_SpiOperation.setItemText(2, _translate("MainWindow", "Write", None))
        self.comboBox_SpiOperation.setItemText(3, _translate("MainWindow", "Erase", None))
        self.pushButton_SpiRun.setText(_translate("MainWindow", "Run", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Spi), _translate("MainWindow", "      SPI      ", None))
        self.pushButton_JtagStartServer.setText(_translate("MainWindow", "Start OpenOCD Server", None))
        self.pushButton_JtagConnect.setText(_translate("MainWindow", "Connect to OpenOCD Server", None))
        self.pushButton_JtagRunGdb.setText(_translate("MainWindow", "Run GDB", None))
        self.lineEdit_JtagElfPath.setPlaceholderText(_translate("MainWindow", "             ELF file location", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Jtag), _translate("MainWindow", "    JTAG    ", None))
        self.lineEdit_I2cFilePath.setPlaceholderText(_translate("MainWindow", "Enter File Name and Path", None))
        self.comboBox_I2cOperation.setItemText(0, _translate("MainWindow", "Find Chip", None))
        self.comboBox_I2cOperation.setItemText(1, _translate("MainWindow", "Read", None))
        self.comboBox_I2cOperation.setItemText(2, _translate("MainWindow", "Write", None))
        self.comboBox_I2cOperation.setItemText(3, _translate("MainWindow", "Erase", None))
        self.pushButton_I2cRun.setText(_translate("MainWindow", "Run", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_I2c), _translate("MainWindow", "       I2C      ", None))
        self.checkBox_d0.setText(_translate("MainWindow", "Pin D0", None))
        self.comboBox_d0.setItemText(0, _translate("MainWindow", "Output", None))
        self.comboBox_d0.setItemText(1, _translate("MainWindow", "Input", None))
        self.checkBox_d1.setText(_translate("MainWindow", "Pin D1", None))
        self.comboBox_d1.setItemText(0, _translate("MainWindow", "Output", None))
        self.comboBox_d1.setItemText(1, _translate("MainWindow", "Input", None))
        self.comboBox_d2.setItemText(0, _translate("MainWindow", "Output", None))
        self.comboBox_d2.setItemText(1, _translate("MainWindow", "Input", None))
        self.checkBox_d2.setText(_translate("MainWindow", "Pin D2", None))
        self.comboBox_d3.setItemText(0, _translate("MainWindow", "Output", None))
        self.comboBox_d3.setItemText(1, _translate("MainWindow", "Input", None))
        self.checkBox_d3.setText(_translate("MainWindow", "Pin D3", None))
        self.checkBox_d7.setText(_translate("MainWindow", "Pin D7", None))
        self.checkBox_d5.setText(_translate("MainWindow", "Pin D5", None))
        self.comboBox_d4.setItemText(0, _translate("MainWindow", "Output", None))
        self.comboBox_d4.setItemText(1, _translate("MainWindow", "Input", None))
        self.checkBox_d6.setText(_translate("MainWindow", "Pin D6", None))
        self.comboBox_d5.setItemText(0, _translate("MainWindow", "Output", None))
        self.comboBox_d5.setItemText(1, _translate("MainWindow", "Input", None))
        self.comboBox_d6.setItemText(0, _translate("MainWindow", "Output", None))
        self.comboBox_d6.setItemText(1, _translate("MainWindow", "Input", None))
        self.checkBox_d4.setText(_translate("MainWindow", "Pin D4", None))
        self.comboBox_d7.setItemText(0, _translate("MainWindow", "Output", None))
        self.comboBox_d7.setItemText(1, _translate("MainWindow", "Input", None))
        self.pushButton_GpioStartInputMonitor.setText(_translate("MainWindow", "Start Input Monitor ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Gpio), _translate("MainWindow", "    GPIO    ", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

